### ISSUE TITLE
[Bug] Villagers cant use Barrel for POI

### ISSUE THREAD

**Issue by xanthian** [Aton-Kish/reinforced-barrels#19]
As above, villager cannot become fishermen with reinforced barrels as they can vanilla barrel.

**Comment by xanthian** [comment]
Its possible your solution to this is breaking a few others mods method of implementation.
https://github.com/quiqueck/BetterNether/issues/39#issuecomment-1215896598

**Comment by xanthian** [comment]
this has sorted it :) and actually made a few modded barrels work that didnt before (blockus/minekea)

**Comment by Aton-Kish** [comment]
Thank you for checking compatibility with other mods<3
