### ISSUE TITLE
Feature Request Barrel Upgrades

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Aton-Kish/reinforced-barrels#8]
Can you make upgrades that can be applied to existing barrels, chests, and shulker boxes like the mods: iron chests and metal barrels?

**Comment by Aton-Kish** [comment]
I think there are some ways to do it.
The easy way is to use the fabric common tags. <https://fabricmc.net/wiki/tutorial:tags>
e.g. c:iron_chest, c:diamond_shulker_box, ...

However, it seems any mod doesn't register metallic storage as common tags.
So this way is not very effective..

By the way, I think iron chest mod and metal barrels mod are forge, but my mod is fabric:_(

**Comment by ClaudiusMinimus** [comment]
Check out [Fabric Iron Chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests-fabric) ([_Source_](https://github.com/TechnoVisionDev/IronChest))

**Comment by ClaudiusMinimus** [comment]
Also, you might be interested to know I have included your mods in my pack [99 Mods on the Wall: Fabric Edition](https://www.curseforge.com/minecraft/modpacks/ninety-nice-99-mods-on-the-wall-fabric-edition), which has almost 400 downloads in the first 24 hours. I hope to get tens of thousands of downloads, which will be good for your mods.

**Comment by Aton-Kish** [comment]
Thank you, but it seems that the common tags are not registered.
e.g. iron_chest.json, means c:iron_chest tag, is not in <https://github.com/TechnoVisionDev/IronChest/tree/master/src/main/resources/data/c/tags/items>

It is difficult if the common tags are not in other mods like the iron chest mod.

**Comment by Aton-Kish** [comment]
> Check out [Fabric Iron Chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests-fabric) ([_Source_](https://github.com/TechnoVisionDev/IronChest))

Thank you, but it seems that the common tags are not registered.
e.g. iron_chest.json, means c:iron_chest tag, is not in <https://github.com/TechnoVisionDev/IronChest/tree/master/src/main/resources/data/c/tags/items>

It is difficult if the common tags are not in other mods like the iron chest mod.
